force-app/main/default/objects/Pomodoro__c/Pomodoro__c.object-meta.xml
<CustomObject>
    <label>Pomodoro</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Pomodoro Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pomodoros</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pomodoro__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>EndDate</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Pomodoro__c/fields/TimeRecorded__c.field-meta.xml
<CustomField>
    <fullName>TimeRecorded__c</fullName>
    <label>TimeRecorded</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OverallAverageController.cls
public with sharing class OverallAverageController {
    
    @AuraEnabled(cacheable = true)
    public static String getOverallDailyAverage() {
        
        List<AggregateResult> queriedDays = [
            SELECT
                DAY_IN_YEAR(EndDate__c),
                SUM(TimeRecorded__c) dailySum
            FROM Pomodoro__c
            WHERE EndDate__c = LAST_N_DAYS:365
            GROUP BY DAY_IN_YEAR(EndDate__c)
        ];
        
        if (queriedDays.isEmpty()) return 'No Records Available';

        Decimal total = 0;

        for (AggregateResult singleDayResult : queriedDays)
            total += (Decimal) singleDayResult.get('dailySum');

        Decimal average = (Decimal) total / queriedDays.size();

        DateTime dt = DateTime.newInstance((average * 60000).longValue());

        return dt.formatGmt('HH\'h\' mm\'m\' ss\'s\'');
    }
}