force-app/main/default/objects/Pomodoro__c/Pomodoro__c.object-meta.xml
<CustomObject>
    <label>Pomodoro</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Pomodoro Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pomodoros</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pomodoro__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>EndDate</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Pomodoro__c/fields/TimeRecorded__c.field-meta.xml
<CustomField>
    <fullName>TimeRecorded__c</fullName>
    <label>TimeRecorded</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DailyAveragePomodoroGraphController.cls
public with sharing class DailyAveragePomodoroGraphController
{
    @AuraEnabled(cacheable = true)
    public static List<AggregateResult> dailyAverage(Integer numberOfDays) {

        return Database.query('SELECT ' +
                'DAY_IN_YEAR(EndDate__c) day ,' +
                'SUM(TimeRecorded__c) dailySum ' +
            'FROM Pomodoro__c ' +
            'WHERE EndDate__c = LAST_N_DAYS:'+ numberOfDays + ' ' +
            'GROUP BY DAY_IN_YEAR(EndDate__c) ORDER BY DAY_IN_YEAR(EndDate__c)');
    }
}